services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BASE_URL=${VITE_API_BASE_URL}
        - SURVEY_CREATOR_LICENSE_KEY=${VITE_SURVEY_CREATOR_LICENSE_KEY}
    container_name: method8_client
    ports:
      - "8080:80"
    restart: always
